# Site settings
title: "/var/log/kamiyaowl"
name: kamiyaowl
description: Tech blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://kamiyaowl.github.io" # the base hostname & protocol for your site e.g. http://materializeblog.com
google_analytics: "UA-135070516-2"

# User settings
profile_img_url: https://avatars0.githubusercontent.com/u/4300987?s=460&v=4
username: kamiyaowl
user_description: Engineer
email: kamiyaowl@gmail.com
github_username:  kamiyaowl
fb_username: ""
twitter_username: kamiya_owl
instagram_username: ""
linkedin_username: ""
disqus_username: ""

# Build settings
markdown: redcarpet
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
    - jemoji

# sass
sass:
  sass_dir: '_sass'
  style: compressed

#links
links:
  - title: Blog Top
    url: /
  - title: "About Me"
    url: "https://kamiyaowl.github.io"
    external: true
  - title: Tags
    url: /tags
